function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 14-Jun-2022 14:12:53

persistent Hd;
persistent Hd1;

if isempty(Hd)
   
    N     = 15;       % Order
    Fstop = 50000;    % Stopband Frequency
    Fpass = 200000;   % Passband Frequency
    Fs    = 1000000;  % Sampling Frequency
    
    h = fdesign.highpass('n,fst,fp', N, Fstop, Fpass, Fs);
    
    Hd = design(h, 'equiripple', ...
        'StopbandShape', 'flat');
    
    set(Hd, 'Arithmetic', 'fixed', ...
        'InputWordLength', 14, ...
        'InputFracLength', 0, ...
        'CoeffWordLength', 16, ...
        'CoeffAutoScale', true, ...
        'FilterInternals', 'Fullprecision');
    
    set(Hd,'PersistentMemory',true);
    
end

if isempty(Hd1)
    
    Fpass = 1000;     % Passband Frequency
    Fstop = 50000;   % Stopband Frequency
    Apass = 1;        % Passband Ripple (dB)
    Astop = 60;       % Stopband Attenuation (dB)
    Fs    = 1000000;  % Sampling Frequency
    
    h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    
    Hd1 = design(h, 'equiripple', ...
        'MinOrder', 'any', ...
        'StopbandShape', 'flat');
    
    set(Hd1, 'Arithmetic', 'fixed', ...
        'InputWordLength', 14, ...
        'InputFracLength', 0, ...
        'CoeffWordLength', 16, ...
        'CoeffAutoScale', true, ...
        'FilterInternals', 'Fullprecision');
    
    set(Hd1,'PersistentMemory',true);
    
end

tiledlayout(4,2)

fs = 1000000; % Sampling frequency (samples per second)
fc = 125000;  
dt = 1/fs; % seconds per sample 
StopTime = 0.2; % seconds 
t = (0:dt:StopTime)'; % seconds
A = 1;
%x1 = sin(2*pi*10000*t)*8192;
fDev = 30000;
%y1 = fmmod(x,fc,fs,fDev);

T = (1/fc)*30;
tt = 0:dt:T+dt ;
x = A*sin(2*pi*10000*tt);
d = fmmod(x,fc,fs,fDev)*8192;

nexttile;
plot(tt,x*8192,'c',tt,d,'b--')
%plot(tt,x);
title('DATA INPUT');
xlabel('SAMPLES');
ylabel('Amplitude');

nexttile;
F_IN = fftshift(abs(fft(d))./length(d));   
plot(tt,log(F_IN)) ;
title('DATA INPUT FFT');
xlabel('Frequency');
ylabel('Amplitude');

y_after = filter(Hd,d);
nexttile;
plot(tt,y_after) ;
title('DATA OUT FROM FILTER 1');
xlabel('SAMPLES')
ylabel('Amplitude')

nexttile;
F_out = cast(y_after,"double")
F_out1 = fftshift(abs(fft(F_out))./length(F_out));   
plot(tt,log(F_out1)) ;
title('DATA OUT FFT');
xlabel('Frequency');
ylabel('Amplitude');


%Fc_sin = sin(2*pi*fc*tt)*8192;
%sum_sin = y_after.*Fc_sin;
s = length(y_after);
H = zeros(s);

for c = 1:s
    if y_after(c,1) < 0
        H(c,1) = 0;
    else
        H(c,1) = y_after(1,c);
    end
end


nexttile;
plot(tt,H);
title('ONLY POSITIVE VALUE');
xlabel('SAMPLES')
ylabel('Amplitude')

nexttile;
F_out2 = fftshift(abs(fft(H))./length(H));   
plot(tt,log(F_out2)) ;
title('DATA OUT FFT 2');
xlabel('Frequency');
ylabel('Amplitude');

data = filter(Hd1,H);

nexttile;
plot(tt,data);
title('DATA OUT FROM FILTER 2');
xlabel('SAMPLES')
ylabel('Amplitude')

nexttile;
F_out3 = cast(data,"double")
F_out4 = fftshift(abs(fft(F_out3))./length(F_out3));   
plot(tt,log(F_out4)) ;
title('DATA OUT FFT 3');
xlabel('Frequency');
ylabel('Amplitude');





